#app
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json
    min-response-size: 512
  port: 8080

#spring
spring:
  profiles:
    active: dev
#  devtools:
#    restart:
#      enabled: false
  session:
    store-type: redis

  #servlet
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true
#  #文件上传大小限制
#  http:
#    multipart:
#      maxFileSize: 50MB
#      maxRequestSize: 50MB
  #mysql数据库配置
#  datasource:
#    initislSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#    filters: stat,wall,log4j
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    dbcp2:
#      initial-size:
#
#  redis:
#    max-active: 8
#    max-total: 50
#    max-wait-millis: 15000
#    test-on-borrow: true
#    max-idle: 10
#    max-wait: 3000
#    min-idle: 0
#    session-expire: 1800
#
##快速数据库连接池druid配置
#druid:
#  loginUsername: admin
#  loginPassword: 123456
#  resetEnable: false
#ceshi

#数据库-实体映射框架mybatis配置
mybatis-plus:
  mapper-locations: classpath:/cn/whu/dhji/mapper/xml/*Mapper.xml,classpath:/cn/whu/dhji/processes/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.whu.dhji.entity
  #typeEnumsPackage: com.whu.biot.entity.enums
  type-handlers-package: cn.whu.dhji.config.mybatis
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义SQL注入器
    #sql-injector: com.whu.biot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
#logging:
#  level: info


